server:
  port: 8070
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    jpa:
      hibernate:
        ddl-auto: create
springfox:
  documentation:
    swagger-ui:
      enabled: true
